# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: '2.1'
orbs:
  android: circleci/android@2.0
jobs:
  test:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.01.29 # Missing required argument(s): tag
    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          system-image: system-images;android-29;default;x86
workflows:
  test:
    jobs:
      - test
